// import favicon from '../public/assets/fonts/logo'

export default function Head() {
  return (
    <>
      <title>J2911-Realty</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/png" href="/favicon.ico" />
    </>
  )
}